# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 459abb32fcfc3ce535164e1645c5c4b5df1232a443268bdbc4b56f5744a07a7a7a3ff33e27a38930fdf0daa0f9c88142b2830b6c530965d582ba43f41489b057

test:
  secret_key_base: e853e59d06dadfe5da774a5c917c4e50b81f96a8bbeb49e965af39fcabbb082b5b282896fc1899f0bacff16cdccf4fd916bdab2cb88913918eef0b9cf21202df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
